name: Deploy Client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist-build
          path: client/dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      #   - uses: actions/checkout@master
      #   - uses: jakejarvis/s3-sync-action@master
      #     with:
      #       args: --acl public-read --follow-symlinks --delete
      #     env:
      #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #       AWS_REGION: "eu-central-1"
      #       SOURCE_DIR: "client/dist"
      - uses: actions/download-artifact@v3
        with:
          name: dist-build
      - run: ls -a
      - run: ls ./clien/dist
